### ISSUE TITLE
Add points percentage to standings. 

### ISSUE THREAD

**Issue by stahnma** [stephenyeargin/hubot-hockey#82]
This matters when teams have played very different numbers of games (see OTT right now). 

` curl -L https://api-web.nhle.com/v1/standings/now | jq '.standings[] | "\(.teamName.default) -- \(.pointPctg)"'`

Is part of the answer.

**Comment by stephenyeargin** [comment]
Concerned about the width of the table on mobile devices. Could have an `HUBOT_HOCKEY_STANDINGS_EXPANDED` config option for L10 and Point %.

**Comment by stephenyeargin** [comment]
See #83
