### ISSUE TITLE
Feature request: Show record for a team

### ISSUE THREAD

**Issue by stahnma** [stephenyeargin/hubot-hockey#95]
When looking up your favorite team, it would be cool to get the record and not just odds to make playoffs.

**Comment by stephenyeargin** [comment]
1. Before a game, it will show the record
2. During a game, it shows the score
3. After a game (and until the `focusedDate` shifts to the next one), it shows the score

Are you wanting to see the record in scenario 2 and 3 as well?

**Comment by stahnma** [comment]
I guess? 

```
21:41 brandon: [03:30:14] !preds
21:41 crunchy: [03:30:15] 10/22/2024 - Bridgestone Arena
21:41 crunchy: [03:30:15]   Boston Bruins         0  
21:41 crunchy: [03:30:15]   Nashville Predators   4  
21:41 crunchy: [03:30:15] Final - https://www.nhl.com/gamecenter/2024020101
21:41 crunchy: [03:30:15] MoneyPuck: 40.5% to Make Playoffs / 2.1% to Win Stanley Cup
```

Maybe display a record there? (I also don't find the MP odds to make playoff helpful until they update the next day, but that's really nitpicking). 

![juuse_saros_no_goals_-_Google_Search](https://github.com/user-attachments/assets/7d1d7b33-54d5-4857-8e74-7af8c53a61ef)

**Comment by stephenyeargin** [comment]
So, one complicating factor and the reason I probably didn't opt for it to begin with: They are only showing the team record for _future_ games in the [feed](https://api-web.nhle.com/v1/scoreboard/nsh/now).

I could grab the current standings (same data as `hubot nhl`) and look up the team, but it might take a bit longer to get a response from the bot. 🤔
